# Generated by Django 4.0.2 on 2022-10-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_addstudents_smobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudents',
            name='smobile',
            field=models.CharField(max_length=10),
        ),
    ]
